<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApplicationIcon>OlivettiLogos.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Pascalina++</AssemblyName>
    <RootNamespace>Pascalina++</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    

  </PropertyGroup>

  <ItemGroup>
    <None Update="OlivettiLogos.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>